version: 2

sources:
  - name: Supabase_data
    database: our-project-93971
    schema: Supabase_data
    tables:
      - name: public_sb_customers_dataset
      - name: public_sb_orders_dataset
      - name: public_sb_order_items_dataset
      - name: public_sb_order_payments_dataset
      - name: public_sb_order_reviews_dataset
      - name: public_sb_products_dataset
      - name: public_sb_sellers_dataset
      - name: public_sb_geolocation_dataset
      - name: public_sb_product_category_name_translation
