version: 2

models:
  - name: dv_category_translation
    columns:
      - name: product_category_name
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_unique
      - name: product_category_name_english
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null

  - name: dv_customers
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 90000
          max_value: 120000
    columns:
      - name: customer_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_unique
      - name: customer_unique_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: customer_zip_code_prefix
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: customer_city
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: customer_state
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "^[A-Z]{2}$"

  - name: dv_orders
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 90000
          max_value: 120000
    columns:
      - name: order_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_unique
      - name: customer_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - relationships:
              to: ref('dv_customers')
              field: customer_id
      - name: order_status
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set:
                - delivered
                - shipped
                - processing
                - approved
                - canceled
                - invoiced
                - unavailable
                - created
      - name: order_purchase_timestamp
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null

  - name: dv_order_items
    tests:
      - dbt_expectations.expect_compound_columns_to_be_unique:
          column_list:
            - order_id
            - order_item_id
    columns:
      - name: order_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - relationships:
              to: ref('dv_orders')
              field: order_id
      - name: order_item_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: product_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - relationships:
              to: ref('dv_products')
              field: product_id
      - name: seller_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - relationships:
              to: ref('dv_sellers')
              field: seller_id
      - name: price
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: freight_value
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

  - name: dv_order_payments
    columns:
      - name: order_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - relationships:
              to: ref('dv_orders')
              field: order_id
      - name: payment_sequential
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: payment_type
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set:
                - credit_card
                - boleto
                - voucher
                - debit_card
                - not_defined
      - name: payment_installments
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: payment_value
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

  - name: dv_order_reviews
    columns:
      - name: review_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: order_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - relationships:
              to: ref('dv_orders')
              field: order_id
      - name: review_score
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 5

  - name: dv_products
    columns:
      - name: product_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_unique
      - name: product_category_name
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: product_weight_g
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: product_length_cm
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: product_height_cm
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: product_width_cm
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

  - name: dv_sellers
    columns:
      - name: seller_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_unique
      - name: seller_zip_code_prefix
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: seller_city
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: seller_state
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "^[A-Z]{2}$"

  - name: dv_geolocation
    columns:
      - name: geolocation_zip_code_prefix
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_unique
      - name: geolocation_lat
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -34
              max_value: 6
      - name: geolocation_lng
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -75
              max_value: -30
      - name: geolocation_city
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: geolocation_state
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "^[A-Z]{2}$"